### ISSUE TITLE
DEVELOPMENT: palaeorotate() function

### ISSUE THREAD

**Issue by LewisAJones** [palaeoverse-community/palaeoverse#11]
I think the palaeorotate() function is more or less there now!

Lucas, could you take a look through the code and documentation? Given your past 6 months of work, you're probably in the best position to give this an initial check before we pass it onto the team for formal review! We also need to think about the comparison (using all PBDB data) between rotations generated via the function, and actually using GPlates (essentially, point rotations vs. grid rotations). Although, I think this is something more for the eventual manuscript.

[11-development-palaeorotate](https://github.com/palaeoverse-community/palaeoverse/tree/11-development-palaeorotate)

Merci!

**Comment by Buffan3369** [comment]
Hi Lewis! That's great, sure I'd be happy to play with it. And about the comparison between actual rotated palaeocoordinates of paleobiodb occurrences and those obtained uing your grid approach, I said I would do this with pleasure. However, I'm a bit running these days between the poster, the MS and some personnal organisation issues. Could you give me a deadline for the revision of your function and the computation of this comparison? That way I can manage to organise myself properely (using your agenda^^).
Hope everything is doing okay in Vigo :)

**Comment by LewisAJones** [comment]
Hi Lucas,

No worries, I don't think any of this needs to be done right now – just when you have chance. Perhaps focus on playing with the function and looking at the code to ensure that it functions as expected (maybe we can achieve this over the next two to three weeks).

I can start work on rotating the PBDB collections (I need to do this as part of another project anyway). Let's touch base when your schedule frees up a bit!

Thanks!

Lewis

**Comment by willgearty** [comment]
Note that there is currently an issue with at least one of the examples for the palaeorotate function (see any recent R CMD check):
```r
❯ checking examples ... ERROR
  Running examples in 'palaeoverse-Ex.R' failed
  The error most likely occurred in:
  > base::assign(".ptime", proc.time(), pos = "CheckExEnv")
  > ### Name: palaeorotate
  > ### Title: Palaeorotate fossil occurrences
  > ### Aliases: palaeorotate
  > 
  > ### ** Examples
  > 
  > #Generic example with a few occurrences
  > x <- data.frame(lng = c(2, 95, 12), lat = c(46, 12, -65), age = c(88, 203, 467))
  > palaeorotate(x = x)
  trying URL 'https://dl.dropboxusercontent.com/s/g5ii9ymu6ew0r7i/Merdith2021.RDS?dl=0'
  Content type 'application/octet-stream' length 9656936 bytes (9.2 MB)
  ==================================================
  downloaded 9.2 MB
  Warning in readRDS(paste0(files, "/Merdith2021.RDS")) :
    lzma decoder corrupt data
  Error in readRDS(paste0(files, "/Merdith2021.RDS")) : 
    error reading from connection
  Calls: palaeorotate -> readRDS
  Execution halted
```

**Comment by LewisAJones** [comment]
Hi Will, I was just checking this. 
Not 100% sure what the issue is as it runs fine from my side. I will investigate more. 
For now, I've included a \dontrun{} on examples. I think the issue is probably due to the function (and examples) downloading data each time it is called, and removing the download at the end of the call.
