### ISSUE TITLE
REVIEW: time_bins()

### ISSUE THREAD

**Issue by KEichenseer** [palaeoverse-community/palaeoverse#12]
Great Job Lewis! I did some tests, it all seems to work except for the binning at large bin sizes (see below). These are the changes I propose:

- [ ] remove `equal` argument: `size` is sufficient. Set default of `size` to `FALSE`, if user specifies a number, then use equal length time bins
- [ ] set `plot` default to `FALSE`: I don't think the user usually doesn't want to plot these intervals when generating time bins.
- [ ] The first bin can be substantially shorter than subsequent bins if long bin sizes are used. Change to generate more uniform bin sizes. Example: time_bins(interval = c("Albian", "Meghalayan"), equal = TRUE, size = 100)
- [ ] add a column called something like "level" to indicate that the bins were grouped on stage, epoch, ... level
- [ ] allow negative ages as arguments to `assign`
- [ ] Input allows epochs, periods ect., but `GTS2020$interval_name` returns only stages. Should return table with stage, epoch, ... column
- [ ] return intervals of time bins as a list of vectors composed of individual interval names, rather than strings with multiple intervals for easier handling in data analysis
- [ ] description unclear: In what way is the mean minimised? I thought the mean durations should be as equal as possible

**Comment by LewisAJones** [comment]
Thanks Kilian! See below for comments:

1, This is a fair comment, it is perhaps redundant to have both arguments. I have updated the function accordingly.
2, plot default set to FALSE. The motivation behind this in the past was to force a visualisation of how uneven bins are temporally. However, I agree, this is not something users would perhaps favour.
3, Hmmm, ok... this could be a problem, and I will need to address it at some point. It will likely require a big overhaul. I don't think the majority of users would carry out this type of binning though, but it is perhaps good to address.
4, 'rank' column now added to indicate the level of bins for both non/equal-length bins.
5, I am not sure we should allow for negative numbers as input. This would require extra transformation of the user's data and could result in some unintended consequences (and confusion from the user's perspective). However, I have added in an error function to detect negative values and inform the user to use non-negative values.
6, Interesting, on my machine GTS2020$interval_name is returning all available names, including those of periods, epoch, etc. Can you double check this?
7, I am not convinced that this is useful to anyone. The point of making these equal length bins is to have a new type of bin. I don't think most users would want to extract individual interval names per bin for some use? In fact, I think this would be annoying to most users who might just want to save the data frame to throw into their SI as their binning strategy? Did you have a particular situation in mind where a user might want to pull out the individual interval names for each bin in other data analysis? Keen to chat more about this!
8, This should read minimises the mean bin length between bins based on the user's specified bin size. i.e. if a user specifies 10 Myr as their target bin size, the function will generate groups of bins that have a mean bin length close to 10 myr. I have now updated this to make it clearer: "In this implementation, intervals are grouped together in a way that minimises the mean bin length between bins based on the user's specified bin size (i.e. if a user specifies 10 Myr as their target bin size, the function will generate groups of bins that have a mean bin length as close to 10 Myr as possible)." Let me know if you have any other suggestions to improve this.

**Comment by KEichenseer** [comment]
Thanks Lewis for acting so fast on this!
5: Good point, however axis_geo() at the moment has a `neg` argument that allows negative ages, we should standardise this
6: Sorry, I missed that. Maybe we could sort the output by level to make it clearer
7 & 8: Discussion was moved to slack

**Comment by LewisAJones** [comment]
Thanks Kilian! 
5: Let's chat about this in the next meeting then. I agree, we should standardise across the board.
6: Or perhaps by age? I do have several columns in the GTS2012/2020 dataframe for sorting via level.

**Comment by LewisAJones** [comment]
I am submitting a pull request for this now, so a quick update regarding points 5 and 6.

5: I have not allowed for negative values as inputs. I fear this could have some unintended consequences. However, I think the error message takes care of this issue in advising the user to transform their data.
6: For now, I am leaving the dataframe sorted by the stage_number index. I think most users will want to access this data most frequently. However, the inclusion of the index column, stage_number, series_number and stage_number allows the user to specify with relative ease the sorting of the dataframe.
