### ISSUE TITLE
User-defined timescale in time_bins()

### ISSUE THREAD

**Issue by willgearty** [palaeoverse-community/palaeoverse#19]
It would be great to give more flexibility to the user to which timescale is being used for `time_bins()` (like `axis_geo()`). This could include incorporating other timescales through `deeptime::getTimeScale()` or by letting the user supply their own dataframe. I imagine this would be most useful for the equal-length binning aspect of `time_bins()`.

**Comment by LewisAJones** [comment]
@ChristopherDavidDean we should try to get this implemented for version 1.1.0. I don't think it will be too difficult tbh.
