### ISSUE TITLE
look_up()

### ISSUE THREAD

**Issue by willgearty** [palaeoverse-community/palaeoverse#25]
The original idea of this function was to provide a conversion table for several regional and international time scales (similar to [GeoWhen](https://timescalefoundation.org/resources/geowhen/)). This seems like a pretty lofty goal, and maybe focusing on a smaller number of time scales would be more tractable (for now). Alternatively, using interval ages to correlate across time scales instead of (bio)stratigraphic correlations might be more manageable and easily updatable?

**Comment by KEichenseer** [comment]
I sent an email to the ICS webmaster Nicholas Car to ask if they have tables or an existing database we could use.

How would you do use interval ages to correlate across time scales? That would work for GTS2012 to GTS2020 with the data we have, but where would you get age information for other stratigraphic systems?

**Comment by LewisAJones** [comment]
Given the difficulty and the maintenance needed for this (as well as decision making from our side), perhaps we should consider having this function set up to match a user-defined table for now. Additional functionality can be added in the future that calls a table we have developed. This way the user is the one making the decisions about what matches what. Until we have some funding to start a proper curation of all these different timescales and matching them... I think this is probably quite a huge (long-term) task. Any thoughts?

**Comment by KEichenseer** [comment]
That's a good idea. What we could do is include our table as an example (it works well with the tetrapod and reef data), with a clear statement that there is no warranty that the assignments in these example tables are 100 % accurate. 
We could implement that as calling our table if the user doesn't provide an interval_key argument?
I'll work on the function in the coming days and next week, let me know if you have further ideas.
