### ISSUE TITLE
tax_unique()

### ISSUE THREAD

**Issue by willgearty** [palaeoverse-community/palaeoverse#27]
A function for removing duplicate taxa from a dataset. I believe this is already performed by the [fossilbrush](https://cran.r-project.org/web/packages/fossilbrush/index.html) package, but I'll leave it up to the assignees to determine if there are any gaps that still need to be filled.

**Comment by LewisAJones** [comment]
I believe the intention with this function is less about removing duplicate taxa as such, and more about identifying taxa which are unique but haven't been identified to a higher taxonomic level. Normal procedures are to remove occurrences not identified to species or genus level. However, removing such data might not always be necessary, and we can make a reasonably interpretation about the existence of potentially additional species. @bethany-j-allen can probably say more on this though!

**Comment by bethany-j-allen** [comment]
Lewis is right, it's complicated to explain but hopefully some examples will help. I've now drafted the function on a new branch, I need to double check a few things and add some more tests but will send a pull request once I've done this, hopefully later this week.
