### ISSUE TITLE
tax_range()

### ISSUE THREAD

**Issue by willgearty** [palaeoverse-community/palaeoverse#28]
A function for calculating the temporal, latitudinal, and/or spatial range of taxa (based on occurrence data).

**Comment by LewisAJones** [comment]
@bethany-j-allen @ChristopherDavidDean I now have a first draft of this function on the tax_range branch developed. Currently for the geographic range, I've gone with using the convex hull method which seems the most popular in palaeo. Temporal and latitudinal range is... well as you'd expect! Let me know your thoughts on the function when you have chance and the implementation. I think it can still be tidied up a bit, particularly with the documentation.
