### ISSUE TITLE
Vignette

### ISSUE THREAD

**Issue by willgearty** [palaeoverse-community/palaeoverse#31]
We should add a vignette to showcase an example workflow using all/most of the functions in the package.

**Comment by LewisAJones** [comment]
Agreed, I have it as a note/task in the manuscript doc 😁

**Comment by LewisAJones** [comment]
The vignette on Phanerozoic reefs is ready to go for the ver. 1.2.0 submission. Any ideas if the tetrapod one will be ready @ChristopherDavidDean @willgearty? How should we proceed if not?

**Comment by willgearty** [comment]
I believe it will also be ready for 1.2.0!

**Comment by willgearty** [comment]
Fixed by #89
