### ISSUE TITLE
Build package website

### ISSUE THREAD

**Issue by LewisAJones** [palaeoverse-community/palaeoverse#36]
At some point, we should establish a website for the package (after we get the first version up and running). This can be done very easily using pkgdown (https://pkgdown.r-lib.org/articles/pkgdown.html). An example of how this can look: https://tidyverse.tidyverse.org/.

**Comment by willgearty** [comment]
I'm happy to work on this (since I'm not working on any PRs at the moment)

**Comment by LewisAJones** [comment]
That would be great @willgearty, thanks! Happy to jump in at some point too. I should be able to wrap up a few of these reviews/PRs this/next week.

**Comment by willgearty** [comment]
We now have a preliminary website at https://palaeoverse.org/! The website should update as we make further changes to the package, including automatically updating the reference pages and adding links to vignettes.

**Comment by LewisAJones** [comment]
Thanks Will! It is looking great already. I plan to work on some of the documentation over the next week so this is great timing. I presume we can also add additional pages if we want to have tutorials, published articles, etc?

**Comment by willgearty** [comment]
That sounds good! And yep, we can link to internal articles or anything on external webpages, it just requires tweaking the yaml file.

**Comment by willgearty** [comment]
Now that we have a bunch of functions, it might be nice to put them into groups in the online manual (see https://ggplot2.tidyverse.org/reference/index.html for an exaggerated example)
