### ISSUE TITLE
tax_spat_expand

### ISSUE THREAD

**Issue by willgearty** [palaeoverse-community/palaeoverse#44]
I can envision a function that is like `tax_time_expand` but for latitudinal bins, although I'm not sure range-through is great assumption for spatial studies. (also, both functions should probably have their names changed to `tax_expand_{spat/time}` to mirror our verb construction of other function names)

**Comment by LewisAJones** [comment]
I agree with updating the function name! I think a `tax_expand_lat` would be a good addition (my preference would be to call it this over `tax_expand_spat` to be consistent with other function names).
