### ISSUE TITLE
Check function and argument names for consistency

### ISSUE THREAD

**Issue by willgearty** [palaeoverse-community/palaeoverse#45]
We should go through the package and check all of the function and argument names for consistency before the CRAN release

**Comment by KEichenseer** [comment]
Had we already reached a conclusion for the argument names of the occurrence input dataframes? 
Specifically, could we just use "occdf" rather than "taxdf" for the tax_check and other tax functions?

**Comment by willgearty** [comment]
I think using `occdf` and `taxdf` where the intended input is occurrences or taxa, respectively, is a good idea, as it just helps reinforce the kind of data the user should be using. For functions where either is allowed (e.g., `tax_unique`), maybe `df` would be ideal?

**Comment by willgearty** [comment]
I also noticed there a few occurrences of plural column names, when really all column names should be singular

**Comment by KEichenseer** [comment]
Good point, `taxdf` makes sense for `tax_expand_lat` and `tax_expand_time`.

**Comment by willgearty** [comment]
Fixed by https://github.com/palaeoverse-community/palaeoverse/pull/54.
