### ISSUE TITLE
Homonym retention in tax_unique()

### ISSUE THREAD

**Issue by bethany-j-allen** [palaeoverse-community/palaeoverse#50]
**Is your feature request related to a problem? Please describe.**
tax_unique() currently verifies repetition based on one taxonomic level at a time. This means that, for example, genera with the same name but in different orders, would currently be collapsed into a single genus.

**Describe the solution you'd like**
The 'if' statements which cross-check taxon names need to be made more nuanced to allow checking across multiple taxon levels.

**Comment by willgearty** [comment]
I wonder if you could just use `group_apply()` recursively to accomplish this?

**Comment by bethany-j-allen** [comment]
I realised that the problem isn't as bad as we first thought - the level of the chosen taxonomic resolution is filtered using a full-column `unique()`, so essentially a mistake will only arise when `resolution = "species"` and the dataset contains generic IDs with the same name but from different higher taxa.

**Comment by LewisAJones** [comment]
Hmmm I am also now stumped :')

**Comment by bethany-j-allen** [comment]
Ah, not quite, it's this:
```
occdf3 <- data.frame(species = c("rex", "aegyptiacus", NA),
                                     genus = c("Tyrannosaurus", "Spinosaurus", "Tyrannosaurus"),
                                     family = c("Tyrannosauridae", "Spinosauridae", "Diplodocidae"))
tax_unique(occdf = occdf3, species = "species", genus = "genus", family = "family")
                      family               genus                   genus_species                    unique_name
1      Spinosauridae     Spinosaurus Spinosaurus aegyptiacus Spinosaurus aegyptiacus
2 Tyrannosauridae Tyrannosaurus             Tyrannosaurus rex            Tyrannosaurus rex
```
The last occurrence is filtered out, because the genus name is already in the dataset, even though in this case the genus belongs to a different family, so should be retained.
