### ISSUE TITLE
tax_unique() output which lists occurrences

### ISSUE THREAD

**Issue by bethany-j-allen** [palaeoverse-community/palaeoverse#51]
**Is your feature request related to a problem? Please describe.**
tax_unique() currently provides a list of 'unique' taxon names, and does not utilise occurrence information.

**Describe the solution you'd like**
An alternative output format which provides occurrence information as nested lists within each 'unique' taxon might be useful.

**Comment by willgearty** [comment]
Can't this be accomplished by using group_apply()?

**Comment by willgearty** [comment]
Ah, I think I was misunderstanding the goal here. You could use `group_apply` for collections to get the different unique taxa within collections, but I agree, if you want the overall list of unique taxa and then the lists of occurrences for those taxa, `group_apply` would not work. I like the idea of just adding the unique name back on to the original df.
