### ISSUE TITLE
tax_range_time example

### ISSUE THREAD

**Issue by LewisAJones** [palaeoverse-community/palaeoverse#60]
The `tax_range_time` example uses orders, but does not exclude "NO_ORDER_SPECIFIED", resulting in weird groupings. This should be updated to use genera or exclude non-specified occurrences.

**Comment by willgearty** [comment]
I was about to just fix this in the example, but it got me wondering: should we just replace "NO_ORDER_SPECIFIED" etc with `NA` in the built-in datasets?

**Comment by willgearty** [comment]
Given @bethany-j-allen recent answer to another issue, I'm guessing we should leave the dataset as-is? I suppose it would be better to make the examples more useful for users with actual PBDB data.

**Comment by bethany-j-allen** [comment]
Hmm. I wrote code to convert these to NA within the tax_unique function, as they are likely to appear often during 'normal' function use. In this case, I don't think they will be relevant as often, so it would be overkill to write it into the function itself. WRT adding removal of these to the example, versus leaving them in to demonstrate a real dataset, I think either is a reasonable choice: with the former, you are demonstrating how to do this if necessary, and with the latter you are staying truer to the dataset.

**Comment by LewisAJones** [comment]
I vote adding a line of code to the example in which we remove these occurrences! Seems the easiest fix and a good example of data preparation steps.
