### ISSUE TITLE
Non-ASCII characters in built-in datasets?

### ISSUE THREAD

**Issue by willgearty** [palaeoverse-community/palaeoverse#61]
[CRAN checks](https://cloud.r-project.org/web/checks/check_results_palaeoverse.html) note that we have some non-ASCII characters in our package. I'm guessing they are within our built-in datasets (maybe characters with accents?)? It's not super urgent, but we should convert them to ASCII at some point.

**Comment by willgearty** [comment]
I investigated this in `tetrapods` and `reefs`, e.g.:
```r
library(tools)
lst <- lapply(tetrapods, function(vec) showNonASCII(na.omit(vec)))
```
`tetrapods` has 311 non-ASCII strings which are all collection names, formation names, stratgroup names, or member names with diacritics/accents or apostrophes. `reefs` has 3 non-ASCII strings which are an author name with weird spaces and two titles with degree signs.

We could easily convert these to non-ASCII characters (e.g., `stringi::stri_enc_toascii`), but it looks like only some CRAN checks even check for this "issue" and it doesn't seem to be a real issue for our package nor for other packages (e.g., [tidyr](https://cran.r-project.org/web/checks/check_results_tidyr.html)).

Given that these non-ASCII characters are representing valid original strings and aren't causing any issues, I'd say we just leave both datasets as-is?

Thoughts @LewisAJones @bethany-j-allen?

**Comment by bethany-j-allen** [comment]
Sounds reasonable to me! The aim of the datasets is to have something as close to user data as possible, so in that philosophy I think we should leave it if it isn't really a problem.

**Comment by LewisAJones** [comment]
I agree with Bethany. Unless this ever develops into an actual issue, I think we're good. You've identified where the issues are so we can quickly fix if need be. Thanks Will!

**Comment by willgearty** [comment]
Sounds good, I'll close this for now!
