### ISSUE TITLE
time_bins fails with defaults for GTS2012

### ISSUE THREAD

**Issue by willgearty** [palaeoverse-community/palaeoverse#62]
While playing around with other things, I realized that `time_bins(scale = "GTS2012")` (i.e., using the old timescale with all other defaults) currently fails. This is because the default value for `interval` is `c("Fortunian", "Meghalayan")`, but the "Meghalayan" stage didn't exist in 2012. To fix/enhance this, I propose that we make the `interval` argument optional (with a default value of `NULL`) and if not specified, all intervals of the desired rank are returned from the specified timescale.

**Comment by LewisAJones** [comment]
The cleanest way to fix this is to change the default for interval to "Phanerozoic". This has now been implemented in https://github.com/palaeoverse-community/palaeoverse/commit/1a7ba2d11755ada5d61d3dd80087f366b79d8cad.
