### ISSUE TITLE
look_up can't assign stages to pre-Phanerozoic intervals and fails if those are present

### ISSUE THREAD

**Issue by KEichenseer** [palaeoverse-community/palaeoverse#63]
**Describe the bug**
The look_up function tries to look up intervals from the GTS tables and assign stages. This fails for intervals older than the Phanerozoic, as older stages are not defined in the GTS tables, resulting in an error. 

**To reproduce**
look_up(reefs,
                      int_key = FALSE,
                      early_interval = "interval",
                      late_interval = "interval",
                      assign_with_GTS = "GTS2020",
                      return_unassigned = FALSE)

**Expected behavior**
Not assign those stages.

**Resolution for the next release**
Add a line of code specifying that pre-Phanerozoic intervals will not be looked up in the GTS tables.

**Comment by LewisAJones** [comment]
Hi @KEichenseer, 

We'd like to submit a new version of the package to CRAN in the next week or so. Do you think you'll be able to submit a PR over the coming days? 

Best,

Lewis

p.s. happy to help with the review or implementation of any changes.

**Comment by KEichenseer** [comment]
Hi @Lewis, no problem, will do that now.

Kilian
