### ISSUE TITLE
Revdep check failure test-axis_geo.R:24

### ISSUE THREAD

**Issue by rsbivand** [palaeoverse-community/palaeoverse#64]
With the devel version of **sf** and **terra**, GDAL 3.6.0, this:
[00check.log](https://github.com/palaeoverse-community/palaeoverse/files/10092530/00check.log)
[testthat.Rout.zip](https://github.com/palaeoverse-community/palaeoverse/files/10092533/testthat.Rout.zip)
The test makes no  sense to me, and setup-data.R also fails:
```
> library(palaeoverse)
> require(divDyn, quietly = TRUE)
>   stages <- deeptime::stages
>   periods <- deeptime::periods
>   data(corals)
Warning message:
In data(corals) : data set 'corals' not found
>   corals_stages_clean <- subset(corals, stage != "")
Error in subset(corals, stage != "") : object 'corals' not found
>   coral_div <- aggregate(cbind(n = genus) ~ stage,
+                          data = corals_stages_clean,
+                          FUN = function(x) length(x))
Error in eval(m$data, parent.frame()) : 
  object 'corals_stages_clean' not found
```
probably explaining why `object 'coral_div' not found`. In my case, `there is no package called 'divDyn'`, but you do not condition on success. Either rewrite the test framework to respect settings where `_R_CHECK_FORCE_SUGGESTS_=FALSE`, or elevate packages needed for testing.

**Comment by rsbivand** [comment]
Installing **divDyn** resolved the problem, but the package is badly broken if tests do not run when **divDyn** is declared as Suggests: but absent. The tests must run even if a Suggested package is not present.

**Comment by willgearty** [comment]
Thanks for reporting this issue @rsbivand. I'll migrate the tests to use the built-in data instead of the data from the divDyn package.

**Comment by rsbivand** [comment]
Sounds sensible. If the original choice is data driven, your could also ask for permission to include a copy in your package.
