### ISSUE TITLE
axis_geo() is backwards on base R phylogenies

### ISSUE THREAD

**Issue by willgearty** [palaeoverse-community/palaeoverse#68]
```r
library(paleotree)
data(RaiaCopesRule)
plot(ceratopsianTreeRaia)
axis_geo()
```

![image](https://user-images.githubusercontent.com/7232514/206577300-5588a4c4-cbea-47d0-8bcd-5d7aa270f577.png)

**Comment by LewisAJones** [comment]
Hey Will, do you need any help with this one or do you have it covered?

**Comment by willgearty** [comment]
I should be good, and might even have the PR up by the end of the day. I'd appreciate your eyes on it then!
